### ISSUE TITLE
Maintaining sync with ionic-super-starter as my own app develops

### ISSUE THREAD

**Issue by brianlmerritt** [driftyco/ionic-starter-super#103]
When I install super-starter via ionic cli, I lose the connection to this repo that I would have if I cloned it.

It's great to have a good kickstart ionic project, but then ionic-native comes along, ionic 3, etc and to use this as my starter I need it to keep up to date with developments AND be able to merge the changes into my own app.

**Comment by danielsogl** [comment]
Hey, we will release the updated template today.

**Comment by brianlmerritt** [comment]
Thanks - that wasn't the issue.

The problem is how do I merge your github changes?  Is there a way to implement super starter from github?  

I tried to merge the master and app branches, but git says they have no shared history.

The only other way I can think of merging new changes to my existing app is to pull down a fresh copy and do a meld, but that is getting painful...

**Comment by danielsogl** [comment]
Ah sorry, I misunderstand your issue.

If you want to sync this "forked" repo with your repo, you should read this guide: https://help.github.com/articles/syncing-a-fork/

**Comment by brianlmerritt** [comment]
Thanks - I can sync a forked repo, but how to install from this repo? If I
git clone and checkout Ionic-3 it doesn't npm install as it's missing
resources and most of the package.json. All those bits are in the app
branch, which won't merge / pull into Ionic-3.

Happy to fork this and push up improved instructions if you can point me on
the right track

**Comment by piotrowski** [comment]
Hi @brianlmerritt - this starter stuff is a bit more complicated as the starters are downloaded and applied (copied over, conflicting files merged) on top of the app-base (which lives at https://github.com/driftyco/ionic2-app-base/archive/master.zip). So if you want to do it yourself, start with the base, then add the super starter.

Additionally the Ionic CLI v3 that just came out temporarily lost the option to install starters from your own Github repo or local directory. But as far as I know this will be added back in soonish.

**Comment by brianlmerritt-kent** [comment]
Thanks - the setup seems quite different than the ionic conference app, which I can install using ionic start myapp conference but can also just fork it, npm install it, modify it, and sync it as it presumably already has ionic2/3-app-base merge in.

**Comment by piotrowski** [comment]
Yep, that's the difference between example apps and starters.

Maybe someone wants to create a "ionic-super-app" and keep it up to date? This would be better for you?

**Comment by brianlmerritt** [comment]
Thanks for your help and support.  There are a lot of great starter apps including this one, but for long term support and learning, I think for my application it's best to build up from the base app from scratch so I better understand and maintain my own services, storage, in-app updates etc.
