### ISSUE TITLE
Error: Cannot find name 'Camera' and Cannot find name 'GoogleMaps'

### ISSUE THREAD

**Issue by davidgv88** [driftyco/ionic-starter-super#107]
# Error
<img width="296" alt="captura de pantalla 2017-05-12 a las 9 20 32" src="https://cloud.githubusercontent.com/assets/679262/25987833/eedcc57c-36f5-11e7-83e8-131c3a6342bd.png">

# FIX
```
ionic plugin add --save cordova-plugin-camera
npm install --save @ionic-native/camera
```

And:
```
ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
npm install --save @ionic-native/google-maps
```

**Would there be any option to automatically install these two packages?**

**Comment by danielsogl** [comment]
I will add them Into the package.json
