### ISSUE TITLE
Suggestion: Use Ionic Auth for signup and login page

### ISSUE THREAD

**Issue by davidgv88** [driftyco/ionic-starter-super#109]
This template could use the Ionic Auth (https://docs.ionic.io/services/auth/) For login and signup pages

**Comment by piotrowski** [comment]
I don't really see Ionic Services like Auth, Push or Deploy in scope for this project. Also you probably wouldn't want a *starter*, but an *example* app that works out of the box - all the Services need some "other" content in the app to make sense.
