### ISSUE TITLE
Bug: Settings Page doesn't display on first run

### ISSUE THREAD

**Issue by abennouna** [driftyco/ionic-starter-super#14]
**Settings Provider**
_Issue_
On app first run (or after clearing storage), when rendering Settings Component’s template using allSettings, template can't find **options**.

_Solution_
In **load()** method, on first run, we must return after **setAll()** promise resolution.

**Comment by denzelwamburu** [comment]
+1
Am also running into this error

**Comment by adirzoari** [comment]
hey, i have problem while i run ionic serve

> Couldn't find ionic.config.json file. Are you in an Ionic project?

I downloaded from github and try run "npm install" into src folder and then ionic serve.

**Comment by denzelwamburu** [comment]
Could you try to run `npm install` in the root folder, not the src

**Comment by abennouna** [comment]
@adirzoari This is not related to the issue.
Anyway, the repo is not working as a standalone ionic project: you should create a project using this template by doing
```ionic start newApp super --v2```
