### ISSUE TITLE
Firefox search doesn't work

### ISSUE THREAD

**Issue by daniel-centore** [driftyco/ionic-starter-super#143]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using in Firefox Quantum 57.0.3, typing in the demo's search bar does not cause any results to show up. 
<img width="587" alt="screen shot 2018-01-02 at 4 33 04 pm" src="https://user-images.githubusercontent.com/569864/34500896-b1103780-efda-11e7-8037-60a79f53a62a.png">

**Expected behavior:**
I expect results to show up, as they do in Chrome.
<img width="499" alt="screen shot 2018-01-02 at 4 32 44 pm" src="https://user-images.githubusercontent.com/569864/34500905-b8a90684-efda-11e7-8154-4c3912349c1b.png">

**Steps to reproduce:**
1. Load the demo in Firefox
2. Skip the tutorial
3. Log in
4. Go to the search tab
5. Type the letter d
6. "Donald Duck" should appear as a result.

**Other information:**
Results do show up in Firefox if I "Inspect Element" anywhere on the page, after having typed my query.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
> ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/dcentore/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by janpio** [comment]
What errors are you getting in your browser's dev tools network tab?

**Comment by daniel-centore** [comment]
All of these messages occurred on initial page load. No new messages arrived when I began to type.

```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
core.js:3565
Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
util.js:60
Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
```

<img width="719" alt="screen shot 2018-01-02 at 5 15 37 pm" src="https://user-images.githubusercontent.com/569864/34502228-9b8e5742-efe0-11e7-98bd-e9b320d8d167.png">

**Comment by janpio** [comment]
These are not from the network tab but console.

**Comment by daniel-centore** [comment]
Whoops, my bad. No errors in the network tab.

<img width="1441" alt="screen shot 2018-01-02 at 7 00 04 pm" src="https://user-images.githubusercontent.com/569864/34504860-350c5b0e-efef-11e7-87ea-c9e7b753cb45.png">

Is it working for you in Firefox Quantum?

**Comment by janpio** [comment]
I currently can't test.

Besides, the correct place to ask (and where the code lives) is now here:
https://github.com/ionic-team/starters/tree/master/ionic-angular/official/super

**Comment by JerryMissTom** [comment]
@daniel-centore add a log "console.log(event.target.value)" in method "onInput($event)", when you type in search bar in FireFox, watch what will happen.

**Comment by daniel-centore** [comment]
@janpio My apologies. Should I continue this thread there then?

@JerryMissTom Adding `console.log(ev.target.value);` to the function `getItems(ev)` in `search.ts` causes whatever is typed in the search bar to appear in the console.

**Comment by janpio** [comment]
Nah, now that @JerryMissTom is also helping you here...

Next step would be to find out why `getItems` doesn't return the expected values - or if it does, why those aren't display.

**Comment by daniel-centore** [comment]
Printing out `this.currentItems` at the bottom of the `getItems` function does include the results.

**Comment by JerryMissTom** [comment]
@daniel-centore could you please provide this demo in your Github, and give the link below, so we can clone and test it.

**Comment by daniel-centore** [comment]
@JerryMissTom It's just the default project with `ionic start projectname super`. I haven't made any changes other than adding the logging.
