### ISSUE TITLE
Cant use custom pipe globally

### ISSUE THREAD

**Issue by REPTILEHAUS** [driftyco/ionic-starter-super#145]
I can import a custom pipe into each individual page module which is fine, however trying to use it in 2 templates throws errors stating that it cant be duplicated and to specify it in a higher module, doing so in app.module doesnt work either as its not available in the pages.. how can I make a pipe available to all pages without importing into each individual page ?

Ive tried to export the pipe from app.module too but it still says it is not available in the pages

**Comment by janpio** [comment]
See https://github.com/ionic-team/ionic-starter-super/blob/master/README.md

**Comment by REPTILEHAUS** [comment]
Sorry but that gives a redirect to another starter and i still dont see any solution to this issue.

From this template the options are:
a) register the pipe in app.module.ts but its not globally available to all the pages
b) register in each individual pages *.module.ts - but this will throw an error that the pipe is being duplicated in the app.

am I missing something ?
