### ISSUE TITLE
Suggestion: Detect language to use in translation

### ISSUE THREAD

**Issue by abennouna** [driftyco/ionic-starter-super#24]
I believe we should detect the device (browser) language, and use it with ng2-translate.

We should also provide the supported language list, and fallback to English if the detected language is not included in that list.

Should I submit a PR?

**Comment by MatanYed** [comment]
Yes it would be great, use cordova globalization!
Just don't forget to use platform.ready and check if platform is cordova, if not, use:
navigator.language || navigator.userLanguage

**Comment by wbhob** [comment]
This is a bit of an advanced implementation that requires native plugins. Ionic Super Starter is designed to be a quick start to demonstrate the basic UI features of Ionic 2, so I don't know if this will happen any time soon. 

However, I recommend creating your own starter project that has shows using a native plugin for localization.

**Comment by abennouna** [comment]
@wbhob it's not clear if you're talking to the OP (me) or the last comment. My suggestion has a (very) simple implementation based on ng2-translate. There have even been 2 PR for it :)

**Comment by danielsogl** [comment]
Hey @abennouna, I implemented that function. Wait for the next release
