### ISSUE TITLE
Suggestion: Update ng2-translate to support directives

### ISSUE THREAD

**Issue by abennouna** [driftyco/ionic-starter-super#25]
Version 4.1.0 adds directive support, and version 5.0.0 listens to translation changes as well when using directives.

**Comment by abennouna** [comment]
Just for the record, that allows writing in the template this:
```<ion-label translate>SETTINGS_OPTION1</ion-label>```

instead of this:
```<ion-label>{{ 'SETTINGS_OPTION1' | translate }}</ion-label>```

Please that there's an [open bug](https://github.com/ocombe/ng2-translate/issues/355), which prevents using of this directive syntax:
```<ion-label [translate]="'SETTINGS_OPTION1'"></ion-label>```

**Comment by AndreasGassmann** [comment]
I personally still prefer using 
`<ion-label>{{ 'SETTINGS_OPTION1' | translate }}</ion-label>`
because it is clear which part gets translated and you can add non-translatable text besides it.

**Comment by abennouna** [comment]
ok but my point is that with the updated version, you can use either way

**Comment by wbhob** [comment]
Both should work, and you're welcome to change it, but using the directive can be tricky for new users, for whom this is designed.

However, you are welcome to make a fork using the directive, and reference it on your blog/README of this repo. It is unlikely that they will pull it into the master branch, but you're welcome to make your own version. 😄 

Please close this issue.

**Comment by abennouna** [comment]
Who said this repo is for new users? If this is the case, the README should state it clearly.

Also, directive vs template interpolation is a matter of preference, but the sole dependency of the Super Starter should be update _nevertheless_, unless something prevents it?
