### ISSUE TITLE
Request: tests and testing infrastructure

### ISSUE THREAD

**Issue by maninak** [driftyco/ionic-starter-super#27]
It would be interesting to see included an already setup (npm dependencies, scripts, etc) testing infrastructure with the proposed tools, and tests (e2e, unit, etc) for the implemented code, using best practices, and as such showcasing how to continue on with our tests the same way the ionic team does, aiming for production quality. 

I love what you are doing with the super-starter and the efforts you invest in helping us use this awesome framework to it's full potential and as easily as possible. I think what I described would be a great addition to complete the development package (and help apps using your framework be of best quality in front of the public).

**Comment by abennouna** [comment]
Just found this: https://github.com/marcoturi/ionic2-boilerplate. Includes Unit & E2E Tests, worth checking!

**Comment by danielsogl** [comment]
Jey @maninak, I close your issue because we created a separate project for e2e and unit tests here: https://github.com/driftyco/ionic-unit-testing-example

Feel free to use it!
