### ISSUE TITLE
Master detail example

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic-starter-super#28]
I am wondering if anyone can provide an example of Master detail layout pattern (AKA split pane) that is mentioned in Max's blog post about this template:

> Today we are releasing the first test version of the Ionic Super Starter, a starter project for new Ionic 2.x apps that comes with over 14 ready to use page designs for common mobile designs like master detail, login/signup, settings, tutorials, and more.

Here is link to ongoing discussion about this feature:
https://github.com/driftyco/ionic/issues/6793

**Comment by mlynch** [comment]
This isn't necessarily a split pane UI, it's a list that links to a detail of a page, with the ability to add/remove items: https://github.com/driftyco/ionic-starter-super/blob/master/src/pages/list-master/list-master.html

**Comment by anderuraga** [comment]
Hello mlynch
I hope this not was a dope question :-( 
I had install other apps in ionic2, but i can´t with this

I can´t install the app, make this steps:
  1.- git clone https://github.com/driftyco/ionic-starter-super.git
  2.- cd ionic-starter-super
  3.- npm install npm -g
  4.- ionic serve

But have one error: 
"Error: ENOENT: no such file or directory, open '....\ionic-starter-super\www\index.html'"


¿ There is a install guide or Readme with steeps for intallaton ?

Thanks a lot of, and sorry by my english

**Comment by abennouna** [comment]
@anderuraga from http://blog.ionic.io/help-us-test-the-super-starter/:

> To test this starter out, install the latest version of the CLI and run:
> 
> ```ionic start myapp super --v2```
> 
>
