### ISSUE TITLE
Error with start Error: No starter template named "super"

### ISSUE THREAD

**Issue by yelhouti** [driftyco/ionic-starter-super#3]
Hi guys, thanks for the great project,

I think `https://github.com/driftyco/ionic-starter-super` should be added to `http://code.ionicframework.com/content/starter-templates.json
` for `ionic start myapp super --v2` to work as in the latest blog post http://blog.ionic.io/help-us-test-the-super-starter/

keep it up !

**Comment by mlynch** [comment]
Yea sorry that went out prematurely, forgot we need the new CLI release (coming today) for this. Thanks!

**Comment by dtslvr** [comment]
How can I fix it? I'm running Ionic CLI v2.1.18

**Comment by abennouna** [comment]
@dtslvr ```ionic start myapp super --v2```

**Comment by gunjank** [comment]
I am still getting same error (today - 01-02-2017). 
 cordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7

λ ionic start myapp super --v2
Creating Ionic app in folder C:\apps\myapp based on super project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip [=============================]  100%  0.0s
**Error with start Error: No starter template named "super"**

Error Initializing app: Error: No starter template named "super"
 Error: No starter template named "super"

**Comment by mlynch** [comment]
hmm, your app lib version is old, but that shouldn't happen. Can you `npm uninstall -g ionic` and install it again?

**Comment by gunjank** [comment]
Thanks @mlynch :+1:  - I have uninstalled ionic (g) and installed it again. Below is ionic info details -
```
Your system information:
 Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
```

And when I tried to run super template : It started downloading and installing like a charm. 
`λ ionic start myapp super --v2`
```
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic-starter-super/archive/master.zip
Installing npm packages (may take a minute or two)...
```
and all good ... after that.
