### ISSUE TITLE
Question: How do I run this project?

### ISSUE THREAD

**Issue by sunny061** [driftyco/ionic-starter-super#32]
I'm just getting into learning ionic 2 and found this repo interesting. However, I can't figure out how to run this project. I've read all the README.md files but couldn't find any instructions there. Some help would be appreciated.

**Comment by AlGantori** [comment]
@sunny061 you are fine believe me, 
These folks don't even review their own documentation.  package.json has none of the ionic2 dependencies.
How do you expect people to get started with this kind "SUPER poor starters".  Also, review and adopt a single pattern in your name you have  "ionic2-starter-blank"  what not "ionic2-starter-super"
"xxxxLoaded" becomes  "xxxxxDidLoad"  WoW!  we are not Martian, we are a still and will always be on earth.

We are dumb as can be.  We download the zip (clone for those super gurus), then unpack the zip, 
start a CLI on the root of these source files.
THEN WHAT?????
npm install ??
Does not do splat!
You have a useless readme and a marketing home page.

Please stop spewing garbage of untested code, examples and upgrade instructions (RC0...RC4).  You are polluting the net with unnecessary posts/bug reports of all kinds.

I am sick and tired of chasing ionic delusive ghosts.
Thank you.

**Comment by jackvial** [comment]
To use this starter template you need to run ```ionic start myapp super --v2```. You can find out more about it [here](http://blog.ionic.io/?utm_source=framework&utm_medium=navbar&utm_campaign=blog%20CTA&_ga=1.160362109.15486423.1464836567) . This was only released to the community to be tested, report bugs and improve it.

@AlGantori Try and be a bit more appreciative of all the hard work that has gone into this project and the fact that you get to use it for free AND remember it is still not production ready so don't expect it to be without it's flaws.

**Comment by sunny061** [comment]
@jackvial Thanks!
