### ISSUE TITLE
Excellent idea!! Thanks for all :)

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic-starter-super#33]
Hi **Ionic Team**!

Thanks for your hard work! Thanks for helping the developers to create good hybrid apps! And thanks for this excellent initiative for the community!! A good starter is the most important! 👍 

PD: I love the logo! We need to improve the **README**! 💯  I want to be a contributor if you want :)

Best regards, Nicholls

**Comment by wbhob** [comment]
The Ionic team appreciates your feedback. However, emailing `hi@ionicframework.com` is a better way to give them your love, as this is a repo for issues people are having with the template.

Please close this issue, and thank you for your kind words!
