### ISSUE TITLE
PWA Content

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic-starter-super#35]
Hi guys,

Include content about **PWA** into the **README** please.

Regards, Nicholls

**Comment by wbhob** [comment]
It's in index.html, just add in `service-worker.js`

**Comment by jdnichollsc** [comment]
Info about **PWA** with **Ionic**, best practices, examples, etc

**Comment by wbhob** [comment]
I just made a PR, should be pulled soon.

**Comment by piotrowski** [comment]
There is nothing special about the Super Starter in relation to PWA - it is just standard. The README only mentions stuff that is special here in comparison to the "blank" starter for example. So I think right now there is no need to change anything at the README. PWA defaults should be covered in the general Ionic Docs.
