### ISSUE TITLE
Cannot find name 'TranslateService'

### ISSUE THREAD

**Issue by timofeysie** [driftyco/ionic-starter-super#37]
After creating the app using:
```
$ ionic start myapp https://github.com/driftyco/ionic-starter-super --v2
```
(as ```$ ionic start myapp super --v2``` failed with the message: Error with start Error: No starter template named "super")

Then, running the app, this error shows up in the browser:
```
Typescript Error
Cannot find name 'TranslateService'.
src/app/app.component.ts
  constructor(translate: TranslateService, platform: Platform, settings: Settings) {
  // Set the default language for translation strings, and the current language.
```

**Comment by davidgv88** [comment]
I have the same problem in Windows. With OS X works ok.

> ionic -v

2.1.18

> node -v

v6.9.2

**Comment by davidgv88** [comment]
https://s30.postimg.org/tb8jkdawx/error1.jpg

https://s30.postimg.org/l70ffmoht/error2.jpg

**Comment by abennouna** [comment]
Can you check whether you have ng2-translate folder in node_modules?

**Comment by davidgv88** [comment]
Hi @abennouna 

The folder ng2-translate not exist in node_modules.

The line ng2-translate not exist in package.json

I use:

> npm install ng2-translate --save

and now works ok!

**Comment by timofeysie** [comment]
@davidgv88's solution works for me as well.  Should I create a PR with ng2-translate added to the package.json?

**Comment by abennouna** [comment]
I asked about ng2-translate because it seems the cause of your original error.

@timofeysie ng2-translate is already present in this starter’s [package.json](../blob/master/package.json).

It looks like the way you started the project, both of you, does not exactly produce the same results than doing it the official way ```ionic start myapp super --v2```.

Can you file an issue reporting that the official command fails on Windows?

**Comment by abennouna** [comment]
Please also check https://github.com/driftyco/ionic-starter-super/issues/3#issuecomment-270011128

**Comment by davidgv88** [comment]
@abennouna Fixed! Thanks!!!

> npm uninstall -g ionic

> npm install -g ionic
