### ISSUE TITLE
ionic serve failed

### ISSUE THREAD

**Issue by jyj545** [driftyco/ionic-starter-super#40]
D:\donghuawork\myapp>ionic serve
Running live reload server: http://192.168.0.84:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://192.168.0.84:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
------------------------------------------------------------------
您被禁止访问互联网

防火墙或防病毒软件可能已阻止您连接到网络。
请试试以下办法：
检查网络连接
检查防火墙和防病毒配置
运行 Windows 网络诊断
ERR_NETWORK_ACCESS_DENIED

**Comment by wbhob** [comment]
That is seemingly a windows problem, so something is wrong with your network. Please talk to your network administrators and close this, or file this bug in english at http://github.com/driftyco/ionic and close it here.
