### ISSUE TITLE
Update tutorial template 

### ISSUE THREAD

**Issue by Fdom92** [driftyco/ionic-starter-super#49]
I tried this super starter and saw that on tutorial page there is a header with no-shadow attribute. Maybe you wanted to use no-border cause the change on RC4. 

> Renamed the no-shadow attribute for Material Design header, footer, and tabs to no-border. This is the same attribute used by iOS mode.

I open an issue cause i think doing a PR with this change its unnecessary.

Thanks for this starter :+1:

**Comment by wbhob** [comment]
Opening a PR for anything is always necessary 😄
I'll just add it into my PR #59

**Comment by Fdom92** [comment]
Why... I wanted to do a PR 😧😧 but no i collaborate in that PR 😄

**Comment by wbhob** [comment]
I can add you to my repo it if you want

**Comment by wbhob** [comment]
Close this?

**Comment by Fdom92** [comment]
yes :)
