### ISSUE TITLE
Suggestion: Update Readme

### ISSUE THREAD

**Issue by abennouna** [driftyco/ionic-starter-super#51]
There's a recurring question on how to use the Super Starter, I believe it's a good thing to add to the readme.

**Comment by jdnichollsc** [comment]
Excellent idea! Maybe to include the most important **Ionic 2** features too? All in one place, excellent help for developers! For example **(Ionic 1 template)** => https://github.com/jdnichollsc/Ionic-Starter-Template

Thanks in advance, Nicholls

**Comment by wbhob** [comment]
@jdnichollsc that can all be found in the docs; every feature is important, and there's no good way to weigh some over others since everyone's needs are different.

**Comment by wbhob** [comment]
Close this?

**Comment by jdnichollsc** [comment]
You can't find the better tips into the docs, a **README** is a good place to find that... Check my starter, It's an excellent help for the community 👍

**Comment by wbhob** [comment]
@jdnichollsc So I took a look at your Ionic-Starter repo, and I can't say I'm not impressed. It's a great way to deep dive into Ionic 1.

A getting started guide exists for Ionic 2 here: http://ionicframework.com/docs/v2/setup/installation/

This repo, again, is designed to ease into Ionic 2 and play around with the features. I think everyone has the same goal in mind, and that is to make it easy to get started with Ionic in one place.

However, perhaps an Ionic 2 tips project/website is in order, combining all the best tools, tips, tactics, blog posts, and tutorials that the Ionic community has created. Interested?

**Comment by jdnichollsc** [comment]
haha thanks my friend, your comments are much appreciated!
And you're right, I'm very obsessed with a good README haha
Regards, Nicholls

**Comment by danielsogl** [comment]
Hey @abennouna, feel free to improve the README and create a PR.

**Comment by piotrowski** [comment]
He did and you merged it 👍 So thanks @abennouna :)
