### ISSUE TITLE
Add moment.js

### ISSUE THREAD

**Issue by MatanYadaev** [driftyco/ionic-starter-super#55]
In the cards page add moment.js pipes, it would be great exercise.

**Comment by wbhob** [comment]
Made a PR: #59

**Comment by wbhob** [comment]
Close this?

**Comment by Fdom92** [comment]
why not this one?? https://date-fns.org/

**Comment by wbhob** [comment]
Moment is a lot more widely used and versatile @Fdom92

**Comment by jdnichollsc** [comment]
yeah, moment is better 👍

**Comment by wbhob** [comment]
Based on previous feedback from Ionic team members, moment will likely not be added because it is one more dependency, and the super starter is designed to be minimal.
