### ISSUE TITLE
template not found

### ISSUE THREAD

**Issue by blondie63** [driftyco/ionic-starter-super#60]
I've this error:
Creating Ionic app in folder /Users/mauro/Documents/Ionic Apps/sp based on super project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Error with start Error: No starter template named "super"

Some help?
Thanks

**Comment by abennouna** [comment]
Please see https://github.com/driftyco/ionic-starter-super/issues/3#issuecomment-270011128

**Comment by wbhob** [comment]
Just update your ionic cli:
`npm install -g ionic`

**Comment by blondie63** [comment]
ok thanks
someone know if i can use nodejs 7.4.0 ?

**Comment by wbhob** [comment]
It is recommended to use the LTS version, which is currently around 6.9.2. I am using 7.2.1, but some things aren't working, so I'm going to roll back.

**Comment by papsl** [comment]
@blondie63 Try using http address instead of template name.

`ionic start myapp https://github.com/driftyco/ionic-starter-super --v2`

**Comment by wbhob** [comment]
Nothing has really happened here for a while, and I think your problem is resolved, can this issue be closed?

**Comment by blondie63** [comment]
ok i close, sorry for delay
