### ISSUE TITLE
App breaks at "New Item -> Add Photo"

### ISSUE THREAD

**Issue by Simsal** [driftyco/ionic-starter-super#76]
Hi,

i started an App today via ionic start myApp super --v2 and deployed it to my Smartphone, a RedMi 3s.

When i try to add a new Item and click onto Add Image, i get to choose different ways.
If i choose one of the pictures out of my Gallery, the App shuts down.

**Comment by FlavioMarquesInf** [comment]
The same problem happens with me, even if i'm using it in the web browser Chrome.

**Comment by danielsogl** [comment]
fixed
