### ISSUE TITLE
Camera - Add Image Not Working  

### ISSUE THREAD

**Issue by JymmiHQ** [driftyco/ionic-starter-super#77]
Hi Ionic Team!

There's an issue in item-create.ts when you try to add an image on Android via the camera. The profilePic remains blank. I've discovered the reason and wanted to share (perhaps you might want to do further testing, but it appears to work). Add destinationType to the Camera options as follows:

```
      Camera.getPicture({
        destinationType: Camera.DestinationType.DATA_URL,
        targetWidth: 96,
        targetHeight: 96
      })
```

Thanks for a great starter template :)

Frank.

**Comment by danielsogl** [comment]
fixed
