### ISSUE TITLE
Replace image item

### ISSUE THREAD

**Issue by agustin-rr** [driftyco/ionic-starter-super#80]
Hello everyone,

congratulations for this template, it's great!!

I have found a bug at Item Create Page (_/src/pages/item-create/item-create.ts_). If you add a image and then you want change it press over the picture again. You get the runtime error:

> Cannot read property 'removeChild' of null

Why remove the file input in processWebImage() method?

Thanks,

**Comment by nebur395** [comment]
Hi,

I have the same problem here. I see no sense to remove the file input in processWebImage() method in: `input.parentNode.removeChild(input);`

Is there any reason why that is removed?

If anyone knows about it, it would be great if he/she could share it with us.

Thanks :)

**Comment by wbhob** [comment]
I agree, it should just be *ngIf'd out IMHO, otherwise it will be completely removed from the DOM and not salvageable.

**Comment by danielsogl** [comment]
@agustin-rr fixed with the next release. Thank you
