### ISSUE TITLE
How do I test this template ?

### ISSUE THREAD

**Issue by Mouradif** [driftyco/ionic-starter-super#87]
Hello,

after running `npm install` I got two errors : 
`
├── UNMET PEER DEPENDENCY @angular/core@^2.0.0

├── UNMET PEER DEPENDENCY @angular/http@^2.0.0
`

then `ionic serve`

`
Couldn't find ionic.config.json file. Are you in an Ionic project?
`

How am I supposed to test this project ?

**Comment by pwespi** [comment]
Use it as a starter template `ionic start myApp super --v2`.
Note that ionic-native has not yet been updated to version 3.x, so there will be some errors at runtime. Take a look at #84 to fix this.

**Comment by Mouradif** [comment]
Okay :) Thanks !
