### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'ion-slides'.

### ISSUE THREAD

**Issue by aberonni** [driftyco/ionic-starter-super#94]
I just created a new ionic project using this starter. I started off with the fixes provided in #84 otherwise I couldn't even compile. Now I am receiving this error.

It seems that it is due to src/pages/tutorial/tutorial.html:

```html
  ...
  <ion-slides [options]="{pager: true}" (ionWillChange)="onSlideChangeStart($event)">
  ...
```

I think [options] is not a property of ion-slides, instead it should be:

```html
  ...
  <ion-slides pager (ionWillChange)="onSlideChangeStart($event)">
  ...
```

This worked for me and it seems to be [documented this way](https://ionicframework.com/docs//api/components/slides/Slides/#input-properties) in ionic docs.

**Comment by aberonni** [comment]
If necessary I can make a quick PR for this.

**Comment by akshayseth** [comment]
What was the fix?
