### ISSUE TITLE
Cannot find module "ionic-native"

### ISSUE THREAD

**Issue by manuelfink** [driftyco/ionic-starter-super#99]
I just installed latest ionic version and wanted to take a look at the super starter, however this fails with the error cannot find module ionic native. What am I doing wrong?

```
ionic start ionic-super super  --v2
cd ionic-super/
ionic serve
```

In the web browser the following error shows up:

```
Runtime Error
Cannot find module "ionic-native"
Stack
Error: Cannot find module "ionic-native"
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at Object.<anonymous> (http://localhost:8100/build/main.js:108352:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:82204:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:120594:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10
Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 6.9.1
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
```

Ionic native is in the package.json and seems to be installed though

`ionic emulate` starts the iphone emulator but the screen stays blank.

**Comment by edmundo096** [comment]
Same issue here.

Noticed that the package `ionic-native` is not installed nor saved in the dependencies as in my other Ionic (v2.x) projects.
So I executed `npm install ionic-native --save`, but it **didn't worked**.

Ended up with the following package.json (fragment):
```
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionic-native": "^3.5.0",
```

**Comment by edmundo096** [comment]
After analysing the `app.component.ts` file, I found that it's quite outdated? Since it still requires the old Ionic 2.x `ionic-native` module.

Better stay off of this outdated _super_ template.

But to remove this error we need to change...

### src/app/app.component.ts
```typescript
import { StatusBar, Splashscreen } from '`ionic-native';
...
constructor(translate: TranslateService, platform: Platform, settings: Settings, config: Config) {
...
StatusBar.styleDefault();
Splashscreen.hide();
```
with
```typescript
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
...
constructor(translate: TranslateService, platform: Platform, settings: Settings, config: Config, statusBar: StatusBar, splashScreen: SplashScreen) {
...
statusBar.styleDefault();
splashScreen.hide();
```

### Then run
```
$ ionic plugin add cordova-plugin-camera
$ npm install --save @ionic-native/camera

$ ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
$ npm install --save @ionic-native/google-maps
```

### src/pages/item-create/item-create.ts
```typescript
import { Camera } from 'ionic-native';
...
constructor(public navCtrl: NavController, public viewCtrl: ViewController, formBuilder: FormBuilder) {
...
  getPicture() {
    if (Camera['installed']()) {
      Camera.getPicture({
```
to
```typescript
import { Camera } from '@ionic-native/camera';
...
constructor(public navCtrl: NavController, public viewCtrl: ViewController, formBuilder: FormBuilder, private camera: Camera) {
...
  getPicture() {
    if (Camera['installed']()) {
      this.camera.getPicture({
```

### src/pages/map/map.ts

Then change in the file the lines, from
```typescript
import { GoogleMap, GoogleMapsLatLng } from 'ionic-native';
...
constructor(public navCtrl: NavController, public platform: Platform) {}
...
    GoogleMap.isAvailable().then(() => {
      const position = new GoogleMapsLatLng(43.074395, -89.381056);
```
to
```typescript
import { GoogleMap, GoogleMaps, LatLng } from '@ionic-native/google-maps';
...
constructor(public navCtrl: NavController, public platform: Platform, private googleMaps: GoogleMaps) {}
...
    this.googleMaps.isAvailable().then(() => {
      const position = new LatLng(43.074395, -89.381056);
```

And comment out the entire content of **src/app/main.prod.ts**

Angular now will complain about Components error and will not render anything.

So, as I said before, better stay out from this _super_ template, and use it only for reference for now.

**Comment by snowyu** [comment]
confirmed.

**Comment by danielsogl** [comment]
Hey @manuelfink, with the next release, this template uses the latest native version.

**Comment by PRINCEHR** [comment]
Guys, I am also facing same issue 
Uncaught Error: Cannot find module "ionic-native"
    at Object.276 (main.js:617)
    at __webpack_require__ (bootstrap 55c373d479ee4bd0c837:54)
    at Object.219 (main.ts:5)
    at __webpack_require__ (bootstrap 55c373d479ee4bd0c837:54)
    at Object.196 (main.js:249)
    at __webpack_require__ (bootstrap 55c373d479ee4bd0c837:54)
    at webpackJsonpCallback (bootstrap 55c373d479ee4bd0c837:25)
    at main.js:1

Any Help to resolve this issue

**Comment by edmundo096** [comment]
@PRINCEHR 
You should post more info like the original poster (versions, OS, etc that the CLI prints). Research how to do it (hint: use `ionic info`). Also try updating your global ionic CLI, and try on a new clean project.
Then either open a new ticket and/or reference this ticket.
